server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5438/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    open-in-view: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
